name: image test
on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  update:
    runs-on: parity-large-new
    steps:
      - run: apt-get update
      - run: apt-get install -y clang libclang-dev unzip build-essential

  sudo-update:
    runs-on: parity-large-new
    steps:
      - run: sudo apt-get update
      - run: sudo apt-get install -y clang libclang-dev unzip build-essential